### ISSUE TITLE
frontoxy.io seem to have expired.

### ISSUE THREAD

**Issue by sebastianmacias** [fabienvauchelles/frontoxy#1]
Not sure if you are still maintaining this project.

**Comment by scrapoxy** [comment]
Hello, it is not expired but I didn't release this project with a proper doc & website.

**Comment by sebastianmacias** [comment]
The readme says:

Documentation
=============

Documentation is on `docs.frontoxy.io`.

.. `frontoxy.io`: http://frontoxy.io
.. `docs.frontoxy.io`: http://docs.frontoxy.io

that's why I thought maybe something wasn't right.

Cheers
